# Generated by Django 5.2.9 on 2025-12-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='類別名稱')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='使用者名稱/登入帳號')),
                ('password', models.CharField(max_length=255, verbose_name='密碼雜湊值')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='電子郵件')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='聯絡電話')),
                ('current_points', models.PositiveIntegerField(default=0, verbose_name='目前點數餘額')),
                ('status', models.CharField(choices=[('active', '活躍中'), ('inactive', '未啟用'), ('banned', '已禁用')], default='active', max_length=10, verbose_name='帳號狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
            },
        ),
        migrations.CreateModel(
            name='MemberAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='market_app.member', verbose_name='會員')),
            ],
            options={
                'verbose_name': '會員常用地址',
                'verbose_name_plural': '會員常用地址',
            },
        ),
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='下單時間')),
                ('final_paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最終支付金額')),
                ('payment_method', models.CharField(choices=[('CASH', '現場現金'), ('LINE_PAY', 'LINE Pay'), ('ALL_PAY', '全支付')], max_length=10, verbose_name='支付方式')),
                ('order_status', models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=10, verbose_name='父訂單狀態')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_orders', to='market_app.member', verbose_name='下單會員')),
            ],
            options={
                'verbose_name': '顧客總訂單 (父訂單)',
                'verbose_name_plural': '顧客總訂單 (父訂單)',
            },
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='攤商名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='攤商介紹')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='攤商聯絡電話')),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Logo 圖片URL')),
                ('approval_status', models.CharField(choices=[('pending', '待審核'), ('approved', '已批准'), ('rejected', '已拒絕')], default='pending', max_length=10, verbose_name='平台審核狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否營業中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('owner_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_stalls', to='market_app.member', verbose_name='攤商管理者')),
            ],
            options={
                'verbose_name': '攤商',
                'verbose_name_plural': '攤商',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('unit', models.CharField(max_length=50, verbose_name='規格/單位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品單價')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('image_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='商品圖片URL')),
                ('status', models.CharField(choices=[('on_shelf', '上架中'), ('off_shelf', '已下架'), ('draft', '草稿')], default='draft', max_length=10, verbose_name='商品狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上架時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='market_app.category', verbose_name='商品類別')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market_app.stall', verbose_name='所屬攤商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('PICKUP', '到攤取貨'), ('DELIVERY', '宅配')], max_length=10, verbose_name='收貨方式')),
                ('order_status', models.CharField(choices=[('received', '已接單'), ('preparing', '備貨中'), ('ready_for_pickup', '可取貨'), ('shipped', '已出貨'), ('completed', '已完成'), ('cancelled', '已取消')], default='received', max_length=20, verbose_name='子訂單狀態')),
                ('parent_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='market_app.parentorder', verbose_name='所屬父訂單')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders', to='market_app.stall', verbose_name='所屬攤商')),
            ],
            options={
                'verbose_name': '攤商獨立訂單 (子訂單)',
                'verbose_name_plural': '攤商獨立訂單 (子訂單)',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='訂購時的單價快照')),
                ('quantity', models.PositiveIntegerField(verbose_name='購買數量')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='market_app.product', verbose_name='商品')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market_app.suborder', verbose_name='所屬子訂單')),
            ],
            options={
                'verbose_name': '訂單商品明細',
                'verbose_name_plural': '訂單商品明細',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='購買數量')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='market_app.member', verbose_name='會員')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='market_app.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '購物車項目',
                'verbose_name_plural': '購物車項目',
                'unique_together': {('member', 'product')},
            },
        ),
    ]
