# Generated by Django 6.0 on 2025-12-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='member',
            table='members',
        ),
        migrations.AlterModelTable(
            name='memberaddress',
            table='member_addresses',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
        migrations.AlterModelTable(
            name='parentorder',
            table='parent_orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='stall',
            table='stalls',
        ),
        migrations.AlterModelTable(
            name='suborder',
            table='sub_orders',
        ),
    ]
