# Generated by Django 6.0.1 on 2026-01-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberaddress',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='詳細地址'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='商品圖片'),
        ),
        migrations.AddField(
            model_name='stall',
            name='close_time',
            field=models.TimeField(default='17:00', verbose_name='結束營業時間'),
        ),
        migrations.AddField(
            model_name='stall',
            name='open_time',
            field=models.TimeField(default='08:00', verbose_name='開始營業時間'),
        ),
        migrations.AlterField(
            model_name='parentorder',
            name='order_status',
            field=models.CharField(choices=[('pending', '待付款'), ('paid', '已付款'), ('cancelled', '已取消'), ('completed', '已完成'), ('ready_for_pickup', '可取貨')], default='pending', max_length=20, verbose_name='父訂單狀態'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='備用圖片URL'),
        ),
    ]
