# Generated by Django 6.0.1 on 2026-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_memberaddress_address_line_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='stalls/', verbose_name='攤商 Logo 圖示'),
        ),
    ]
